apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: annabelladb-master
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: annabelladb-master-deployment
  labels:
    name: annabelladb-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: annabelladb-master
  template:
    metadata:
      labels:
        name: annabelladb-master
    spec:
      hostname: annabelladb-master
      subdomain: default-subdomain
      containers:
      - name: annabelladb-master
        image: szalay/master_annabelladb_k8s
